- commands/args.go
- commands/args_test.go
- commands/commands.go
- commands/commands_test.go
- commands/flag.go
- commands/release.go
- commands/runner.go
- git/git.go
* It preserves global flags like `-c`
* It preserves global `COMMAND --help`
* Some refactorings
This fixes https://github.com/github/hub/issues/763 and https://github.com/github/hub/issues/756
> Properly parse global flags:

- .travis.yml
- CONTRIBUTING.md
- Vagrantfile
Go 1.4.1 has some bug fixes for 1.4: https://github.com/golang/go/issues?q=milestone%3AGo1.4.1. Nothing is changed on our side.
> Bump to use Go 1.4.1

- script/package
Tarballs are traditionally .tar.gz, not .gz.tar
This can be seen in the tarballs for 2.2.0-rc1 provided on https://github.com/github/hub/releases
> Fix package's file extensions

- commands/updater.go
- features/support/env.rb
- fixtures/test_configs.go
- github/config.go
- github/crash_report.go
This fixes Windows issue: https://github.com/github/hub/issues/772. It also includes renaming of some environment variable names starting with `GH_`.
> Get home dir using `user.Current()` if `HOME` env var is not set

- commands/checkout.go
- features/checkout.feature
Start reading the `Head.Repo.Name` property from API payload to determine the name of the forked repo which might not match the name of the base repo.
Fixes #768
> Fix `hub checkout <PULLREQ-URL>` for renamed fork

- script/version
so that the version number is always echoed on stdout.
With this change, the version script will print a version
number even if git or the ".git" directory are not available
like in the "release-source.tar.gz" archive.
> don't exit when "git rev-parse" fails

- script/package
This is to improve package script in two ways:
1 Add man pages to build package
2 Rename package name as `hub_OS_CPU_vVERSION`. Ending package name with `vVERSION` allows Homebrew to recognize the build version in `brew install`. See https://github.com/boxen/puppet-hub/pull/10#issuecomment-71783691
> Refine package scripts

- commands/init.go
- commands/init_test.go
Now the optional `directory` argument to `git init` is detected by looking for the first "word" in arguments that isn't a value for one of `--template`, `--shared`, or `--separate-git-dir` params.
This is done by simply iterating through args instead of pulling in a full-blown flag-parsing library. This is also the approach we take in the `clone` command.
This is an alternative implementation to #793. @jingweno, let me know what you think.
Fixes #792
> Better arguments processing for `init` command

- commands/utils.go
- commands/utils_test.go
`bufio.Scanner` takes care of line endings difference for different OSes. See http://golang.org/pkg/bufio/#ScanLines.
This fixes #805
> Read title and body by taking into account Windows line endings

- commands/merge.go
- features/merge.feature
`hub merge --squash PULL_URL` fails with:
```
You cannot combine --squash with --no-ff
```
This PR is to replace https://github.com/github/hub/pull/796 by adding tests.
> merge: do not insert "--no-ff" for "--squash"

- README.md
This is to remove 1.x installation instruction to avoid confusion.
Homebrew formula has been merged: https://github.com/Homebrew/homebrew/commit/69096c85c710679a83fbc32d9950d42668707aec
> Only keep 2.x installation instruction since it’s released

- index.html
See https://github.com/Homebrew/homebrew/commit/69096c85c710679a83fbc32d9950d42668707aec
> gh pages: `hub` homebrew formula doesn’t require `—HEAD` now

- commands/args.go
- commands/args_test.go
- commands/checkout.go
- commands/checkout_test.go
`Args.InsertParam` panics about index out of bound if the index is larger than param size. These changes reset the index to param size for such case. This is equivalent to appending new items to the end.
This fixes #812.
> `Args.InsertParam` resets index to param size if it’s out of bound

- commands/alias.go
- commands/ci_status.go
- commands/commands.go
- commands/commands_test.go
- commands/create.go
- commands/issue.go
- commands/release.go
- commands/runner.go
- commands/updater.go
- commands/version.go
- github/config.go
- github/crash_report.go
- ui/ui.go
- utils/utils.go
Introduce a `console` package which encapsulates logic of printing out
to console. This provides flexibility of discarding output in tests.
It also allows us to unify format of printing to console (if we want to).
This fixes #801.
> Extract logic of printing out to console

- commands/checkout.go
- commands/merge.go
- commands/utils.go
- features/checkout.feature
- features/merge.feature
To obtain the owner/fork-name combo, instead of reading it from "label" field from the PR response simply read from `Head.Ref` and `Head.Repo.Owner.Name` instead. This is because label is meant to be human-readable, isn't well-documented in GitHub API docs, and is unclear when it contains two components (delimited by `:`) or when it contains only one.
Maybe fixes #816
> Avoid using "label" field when parsing PR response

- commands/checkout.go
- commands/merge.go
- features/checkout.feature
- features/merge.feature
It is `headRepo.Owner.Login` that holds the unix account name of the
owner, and `headRepo.Owner.Name` is omitted from the embedded owner
information, resulting in the following failure:
```
% hub checkout https://github.com/github/hub/issues/{number}
fatal: '' is not a valid remote name
```
> Use `.Login` instead of `.Name` for generating a remote or branch name.

- git/ssh_config.go
- git/ssh_config_test.go
I had a cryptic problem because the ssh config reader is case-sensitive, while ssh itself is not:
> [servconf.c@520](http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/ssh/servconf.c?annotate=1.260):
> ``` c
if (strcasecmp(cp, keywords[i].name) == 0) {
*flags = keywords[i].flags;
return keywords[i].opcode;
}
```
In my case, I had something like the following in my ssh config (note the lowercase "h" in `host other`):
```
Host github.com
HostName ssl.github.com
Port 443
host other
HostName 10.0.0.1
```
This caused the url to be written with 10.0.0.1 used as the host replacement. This was, subsequently, causing operations like `pull-request` to fail because remotes with `github.com` were no longer being recognized as being github (because of the rewrite).
> Make the ssh config reader case-insensitive

- github/project.go
- github/project_test.go
`useHttpProtocol` has been changed to a more generic `useProtocol`
function that can be used to check more than just https. This allows us to
use the SSH protocol in any location, regardless of the repository being
private or public.
```
% git config --global hub.protocol ssh
% ./hub --noop clone github/hub
git clone git@github.com:github/hub.git
% git config --global hub.protocol https
% ./hub --noop clone github/hub
git clone https://github.com/github/hub.git
% git config --global hub.protocol none
% ./hub --noop clone github/hub
git clone git://github.com/github/hub.git
```
(Got tired of waiting for #599 :) )
> useHttpProtocol => useProtocol, allow ssh config

- script/build
GNU find(1)'s -not operator is not POSIX compliant.  Use ! operator
instead in order to work with other find(1) implementations.
> fix non-portable GNU find(1)-ism

- README.md
- commands/checkout.go
- commands/cherry_pick.go
- commands/cherry_pick_test.go
- features/checkout.feature
- features/cherry_pick.feature
- man/hub.1
- man/hub.1.html
This is so the tags from the automatically-added remote (typically someone's fork) don't spill in and mix with the current tags.
Fixes #879
> Use `--no-tags` for new remotes in `checkout/cherry-pick`

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/howeyc/gopass/pass.go
- Godeps/_workspace/src/github.com/howeyc/gopass/win.go
Bumping to the latest gopass. This fixes https://github.com/github/hub/issues/837.
> Fix password insertion more than 15 characters on Windows

- git/git_test.go
`git var` checks the `$GIT_EDITOR` environment variable before the `core.editor` config knob. `TestGitDir` intends to verify that the latter is respected, so sanitize the environment before running the test and restore it upon completion.
> Fix spurious test failure when GIT_EDITOR is set

- commands/args.go
- commands/args_test.go
- commands/help.go
- commands/runner.go
- commands/version.go
Now, every argument except `--help` and `--version` that starts with a `-` is considered to be a global flag. In the long run, this ensures that hub deals with global flags that git might add in the future.
Alternative to https://github.com/github/hub/pull/942
/cc @whilp
> Avoid depending on a hardcoded list of git global flags

- commands/pull_request.go
- etc/hub.bash_completion.sh
- etc/hub.zsh_completion
- features/bash_completion.feature
- features/pull_request.feature
- features/zsh_completion.feature
- github/client.go
- man/hub.1
- man/hub.1.html
- man/hub.1.ronn
Add the `-M/--milestone` and `-l/--labels` flags to `hub pull-request` to
set the milestone or tags when a pull request is created.
Signed-off-by: David Calavera <david.calavera@gmail.com>
> Allow to set pull request milestone and labels.

- commands/updater.go
- commands/version.go
- github/crash_report.go
- script/build
- script/package
- version/version.go
This adds running command and hub version to crash report. It includes refactoring of hub version to the `version` package for reusability in `commands` package and `github` package.
> Improve crash report with command and version

- commands/ci_status.go
- features/ci_status.feature
- features/steps.rb
- github/client.go
- github/client_test.go
- github/config.go
- github/http.go
- github/util.go
- man/hub.1
- man/hub.1.html
- man/hub.1.ronn
Now `ci-status` consumes the new combined statuses API endpoint designed for when multiple contexts report statuses independently.
The verbose output is now colorized and is in format where each line is:
✔︎ <Tab> [CONTEXT] <Tab> [URL]
Fixes #943
@jingweno Since Octokit only supported the old API endpoint and I needed access to the new one, here I did an experiment called "simple client" where I bypassed Octokit and used net/http and JSON parsing directly. I wanted to see how much would be involved, because for some future commands I need to do certain things that Octokit doesn't support and I don't have the bandwidth to maintain both libraries right now. What do you think?
> Enhance `hub ci-status` to consume and display combined statuses

- commands/compare.go
- features/compare.feature
> Fix `compare` crash when used on a non-GitHub repo

- index.html
the other two headers ("As a ...") are attributive, that one was predicative, which was kind of inconsistent and also the "one who" construction just seemed off.
> unawkward the work header a bit

- README.md
- etc/README.md
Added a README to the folder `etc` containing instructions on how to use the `hub.zsh_completion` file.
> Add installation instructions for zsh tab-completion

- git/git.go
From git documentation:
-C <path> : Run as if git was started in <path> instead of the
current working directory. When multiple -C options are
given, each subsequent non-absolute -C <path> is
interpreted relative to the preceding -C <path>.
We correctly forwarded the `-C <path>` values as git global flags to git invocations such as `git rev-parse --git-dir`, but that command is designed to return the result as a relative path to the value computed from `-C`. This adds an extra step to transform this relative path to an absolute one by applying values of `-C` as the base directory.
Fixes #1020
> Properly support `-C` git global flag

- cmd/cmd.go
- commands/ci_status.go
- github/config.go
- github/http.go
- github/util.go
- ui/ui.go
Previously, HUB_VERBOSE only logged HTTP interactions. Now, it also logs any external command invocations (typically to `git`) to stderr as well, although in a color different from HTTP.
> Have `HUB_VERBOSE` also log externally run commands

- git/git.go
It's invoked often from different methods, but always has the same results. Cache it after the 1st run so subsequent runs are no-ops.
Before:
HUB_VERBOSE=1 git browse
$ git config alias.browse
$ git rev-parse -q --git-dir
$ git rev-parse -q --git-dir
$ git remote -v
$ git rev-parse -q --git-dir
$ git config hub.host
$ git rev-parse -q --git-dir
$ git config push.default
$ git rev-parse -q --git-path refs/remotes/origin/no-angular
$ git rev-parse -q --git-dir
$ git rev-parse -q --git-dir
$ git rev-parse -q --git-dir
After (6 fewer invocations):
HUB_VERBOSE=1 git browse
$ git config alias.browse
$ git rev-parse -q --git-dir
$ git remote -v
$ git config hub.host
$ git config push.default
$ git rev-parse -q --git-path refs/remotes/origin/no-angular
> Cache result of `git rev-parse --git-dir`

- commands/fork.go
- features/fork.feature
Fixes nil reference crash. Fixes #1042.
> commands/fork: handle missing "origin" remote

- commands/clone.go
`hub clone` doesn't need the directory parameter.
Felt that changing the long description became too much text. Let me know if you want it.
e.g.:
```go
Long: `Clone repository "git://github.com/USER/REPOSITORY.git" into
DIRECTORY as with git-clone(1). When USER/ is omitted, assumes
your GitHub login. When [DIRECTORY] is omitted assumes REPOSITORY.
With -p, clone private repositories over SSH.
For repositories under your GitHub login, -p is implicit.
`,
```
> document that clone directory is optional

- commands/alias.go
In instances where the `SHELL` environment variable is not set, nor is the `-s` parameter set it is not clear what action should occur.  Clarify the error message to make it obvious.
Closes #1065
Untested.
> Clarify "Unknown Shell" Error Message

- github/client.go
- github/config.go
- vendor/github.com/mitchellh/go-homedir/LICENSE
- vendor/github.com/mitchellh/go-homedir/README.md
- vendor/github.com/mitchellh/go-homedir/homedir.go
- vendor/github.com/mitchellh/go-homedir/homedir_test.go
Stop using `user.Current()` since that seems to cause problems for people who are using cross-compiled hub on certain systems.
No idea if this will surface further cgo issues, but it's a start.
Fixes #1058, fixes #781
> Avoid "user: Current not implemented" error

- cmd/cmd.go
- commands/clone.go
- commands/fetch.go
- commands/utils.go
- features/clone.feature
- features/fetch.feature
- features/steps.rb
- git/git.go
In `hub clone NAME`, "NAME" was previously considered a local resource if a directory of the same name existed, and the clone command was left unchanged.
That worked for a while, but some users were surprised that they couldn't clone their repo named "NAME", only to discover that there was an unrelated directory "NAME" in the current working directory.
Also, a git bundle is a valid cloneable resource, but is a file and not a directory.
This refines the detection of cloneable resources. "NAME" is considered to be locally cloneable if one of the following is true:
- `NAME/.git` exists
- `NAME` is a bare git repo
- `NAME` is a file whose first line includes "git bundle"
Fixes #898
> Improve detecting local clone resources

- commands/help.go
- features/help.feature
- features/support/fakebin/man
- git/git.go
- We no longer hardcode git help text within hub, risking it to fall out of date. Instead, regular `git help` is displayed, and hub just appends its own bit to it.
- `hub help hub` now executes `man hub`. Fixes #977
> Help text improvements

- script/install.bat
setx automatically truncates the PATH to 1024 characters if it is longer than that, which is no good. It also mucks up the local user's PATH with the machine-wide PATH.
This PR fixes that by using PowerShell to manually alter the PATH.
> Don't corrupt the PATH if longer than 1024 characters on Windows

- features/support/env.rb
This shouldn't affect the CI, but it makes easier to test on my locale machine given that git runs with my current locale (which is not english) thus the git messages were different from what those tests expect.
> Make tests more robust to various Locales.

- commands/release.go
- features/release.feature
- github/client.go
- github/http.go
This is probably overly simplistic, it downloads all assets if there are any, writes them in the current directory and prints the names.
I was lazy and avoided touching octokit.
Addresses #1102
> Add `hub release download` command that downloads all assets.

- commands/pull_request.go
The description for --head said it was the head branch instead of head branch.
> Fix copy-pasta

- index.html
- Improve readability by improving color palette.
- Increase visual contrast between colors.
- Improve readability of the CSS source code.
- Increase line-height for comments.
- Change footer text from github to GitHub.
- Change background color to match logo color palette.
- Change section border-radius from 6px to 4px.
- Add missing semicolons to reduce potential for errors.
Main goal of the changes is to improve the visual style.
*New visual style*
*Old visual style (for comparison)*
> docs(website) improve visual style and readability

- github/client.go
Git Hub Enterprise requests should always include /api/v3 in the URL in order to hit the correct API endpoint. The ci-status and release commands were producing the wrong request URL.
```
> GET https://[GHE URL]/repos/[ORG]/[REPO]/commits/[SHA]/status
```
rather than:
```
> GET https://[GHE URL]/api/v3/repos/[ORG]/[REPO]/commits/[SHA]/status
```
As result, an LDAP authentication page was returned rather than the expected JSON. A parsing error could be seen:
```
invalid character '<' looking for beginning of value
```
This commit changes the construction of the request URL for the ci-status and release commands, making sure the existing client.requestURL function is called. This makes sure the API request always hits the right endpoint in Git Hub Enterprise.
> Fix #1100: Append /api/v3/ to request when using GHE

- etc/hub.bash_completion.sh
Not super portable, but a step forward.
> bashcomp: try to load git comp first (fix #592)

- script/bootstrap
There might be a bundle config that specifies a different path, which
breaks the build. Explicitly specifying the path changes that.
> Explicitly specify binstub path in scripts/bootstrap

- commands/issue.go
- commands/issue_test.go
- features/issue.feature
- ui/format.go
- ui/format_test.go
This will be used to choose the formatting of issues (in `hub issue`) or pull requests (in `hub pr`).
> Use a formatter to choose the display of issues like `git log --format`.

- features/pull_request.feature
- github/client.go
According to Github's API docs, creating a pull request should yield a
status code of 201 and not 200.
Closes #1226
> Fix CreatePullRequest to expect 201 over 200

- commands/help.go
Remove (beta) from help.go for release and issue.
Feature has been in since 2013? Should it graduate from Beta now? :)
> Graduate from beta

- features/issue.feature
- github/client.go
There was a typo in Issues struct which try to parse the legacy field `assignee` (notice the singular) as array instead of the new field `assignees`.
Fixes #1233
/cc @pcorpet
> Fix listing assignees in `hub issue`

- commands/checkout.go
- commands/checkout_test.go
- features/checkout.feature
Update hub checkout not to create any new remotes thus leaving less tracks behind.
> Reimplement hub checkout to avoid creating unnecessary remotes

- commands/issue.go
- commands/pull_request.go
- commands/pull_request_tpl.go
- fixtures/test_repo.go
- github/template.go
- github/template_test.go
This pull request includes all the changes from #1145, including changes
made by @ganmacs and @NickLaMuro, with two small additional fixes on top
of those.
The reviewer is encouraged to see the conversation in #1145.
This pull request itself includes changes that
- Allow for hub to populate the EDITOR with pull request and issue
templates
- Correctly search for such templates, considering things like
case-insensitivity and file extension. See [the GitHub docs][1] for
more information.
- Test that the above features work as intended.
Supercedes #1145.
Closes #446, #937, #964, #1118.
[1]: https://help.github.com/articles/helping-people-contribute-to-your-project/
> Issue and Pull Request Templates, with addendums

- commands/pull_request.go
- features/pull_request.feature
Hi. ```-e``` option improves pull-request with template.
For example 
run ```pull-request -F template_file -e``` then open editor and configure a template file. :tada: 
related issue: https://github.com/github/hub/issues/446
> Add -e option to pull request

- commands/issue.go
- features/issue.feature
> Add missing filters when listing issues.

- commands/args.go
- commands/browse.go
- commands/compare.go
- commands/create.go
- commands/fork.go
- commands/issue.go
- commands/pull_request.go
- commands/release.go
- commands/utils.go
- features/create.feature
- features/release.feature
- vendor/github.com/atotto/clipboard/LICENSE
- vendor/github.com/atotto/clipboard/README.md
- vendor/github.com/atotto/clipboard/clipboard.go
- vendor/github.com/atotto/clipboard/clipboard_darwin.go
- vendor/github.com/atotto/clipboard/clipboard_unix.go
- vendor/github.com/atotto/clipboard/clipboard_windows.go
Commands `create`, `issue create`, `pull-request`, and `release create` now consistently support `-c/--copy` option to copy the new URL to clipboard and `-o/--browse` option to open the new URL in the web browser.
Fixes #182, fixes #1111
> Enable copy to clipboard functionality for commands that print URLs

- Makefile
- commands/runner.go
- commands/sync.go
- features/browse.feature
- features/pull_request.feature
- features/steps.rb
- features/support/env.rb
- features/sync.feature
- git/git.go
- share/man/man1/hub.1.ronn
Ported from [my bash version](https://github.com/mislav/dotfiles/blob/370154a5adc482afd89606c126bcd18df2560013/bin/git-sync).
Here was it in action: https://twitter.com/mislav/statuses/677091160482054144
Unlike GitHub Desktop, the sync command **doesn't ever push any branches**. It only deals with incoming changes from upstream. Should it be pushing branches?
Fixes #906, fixes #618
> New `hub sync` command to update local branches

- index.html
This makes the commends stand out less in the page, easier to read.
> Changing comment color to gray-ish (matching github's)

- commands/checkout.go
- features/checkout.feature
When there is already a git remote for the head repo of a PR to be checked out, fetch the corresponding branch from that remote instead of fetching the special `refs/pull/XY/head` ref.
This sets up a pull/push workflow for branches that the user might have write access to.
Fixes #1238
/cc @blueyed
> Reuse existing git remote for PR head in `checkout`

- script/install.sh
on each ``` man hub* ``` commands in the shell, the shell reports
``` warning: ignore bogus filename```  for the respective .txt present
in the man path.
copying only the man file to the man path solves this issue.
> don't copy .txt files to man path

- commands/pull_request.go
- features/pull_request.feature
- git/git.go
This removes an extra step from the process of publishing a pull
request. It also gives the user a chance to back out of the entire
process by saving an empty pull request message.
> Add a --push flag to hub pull-request.

- github/editor.go
You are overriding the filetype set by the user using the -c option. This makes
it hard to set a filetype in the vimrc.
> Use --cmd instead of -c to set default filetype for vim

- commands/pull_request.go
- features/pull_request.feature
This ensures that a branch pushed using "hub pull-request" has its
upstream branch set to the target of the push.
> Add --set-upstream to git push commands.

- commands/browse.go
- features/browse.feature
The -c parameter will put the url into the clipboard instead of opening in the browser.
> Add clipboard copy (-c) to browse command

- commands/checkout.go
- features/checkout.feature
- features/steps.rb
- features/support/fakebin/git
- github/client.go
- github/project.go
When checking out a pull request that doesn't match an existing remote,
this sets the branch's remote and merge configuration fields. If the
pull request is modifiable by the maintainer, it uses the SSH URL to
that you can push to the pull request.
> Set merge configuration on checkout.

- commands/issue.go
- features/issue.feature
This change adds a long-form flag `--show-pulls` to `hub issue` that directs hub to include pull requests in the issue listing.  The default value is false; the default behavior does not change.
Temporary fix until a better abstraction for pull requests can be designed in #1303.
Related: vermiculus/magithub#44
> Add option to show pull requests again

- commands/fork.go
- features/fork.feature
Allows the user to choose the remote name for their fork instead of
always using their GitHub username. This is useful for workflows where
folks name the remote for their private fork origin `origin` and
the upstream repo remote is named `upstream`. We happen to use this
workflow at work, because it makes the remote names more predictable and
easy to manage (you always push your new commits to `origin` rather than
a remote name that is dependent on your username).
I also made a small change to allow `hub fork` to not fail if there is no
remote named `origin` but there **is** a remote named `upstream`.
```
$ hub clone --origin=upstream github/hub
Cloning into 'hub'...
remote: Counting objects: 13748, done.
remote: Total 13748 (delta 0), reused 0 (delta 0), pack-reused 13747
Receiving …
```
> fork: Add --remote-name option

- commands/release.go
- features/release.feature
`hub release` currently list all non-draft releases, with an optional flag to include drafts. However, there is no way to list only full releases. This adds an `--exclude-prerelease` flag which omits all prerelease release from the output.
> Added release flag to exclude prereleases.

- features/fish_completion.feature
Before this change, the `pu` would sometimes expand to `pull
pull-request push` if the order isn't important, we should take this
fix.
However, if the order is important, we should probably switch the
expectation such that the options are presented alphabetically as
observed.
> Allow the unsorted expansion for the fish shell

- features/support/completion.rb
However my git installation was run, it installed the
git-completion.{bash,zsh} scripts under
"${GIT_PREFIX}/contrib/completion/" instead of any of the paths that
this test case was expecting.
To make matters worse, the only way to know that this was the problem
was that each scenaro failed with a message about timing out while
waiting for completion to happen in tmux. Just in case there are
other paths out there where the git-distributed completion scripts
may live, I've also added some detection logic to raise an exception
during the "Given" clause of the scenario if we cannot find the
git-distributed bash completion scripts in any of the places we're
looking for them. This would have made it a lot easier to diagonse
the failures.
> Fix bash completion test on MacOS X

- cmd/cmd.go
- github/editor.go
- github/reset_console.go
- github/reset_console_windows.go
This pull request resets stdin to be read from the current console on unix based system.
To avoid the vim error 'Vim: Warning: Input is not from a terminal'
When reading in the pull request message from stdin and editing it afterwards.
For example the following command will no longer causing issues for a terminal (Which is the command I used to create this pull request)
```
(git rev-parse --abbrev-ref HEAD 2>/dev/null;(git diff --no-color -M --patch-with-stat  github/master...HEAD | perl -pi -e's/^/#/') )  | hub pull-request -b github:master -F - --edit
```
Fixes #1481
> reset-console

- commands/help.go
- features/help.feature
The rest of the sections are sorted alphabetically. This makes the hub commands easier to read by sorting them the same way.
> Sort hub commands

- script/build
- script/ruby-test
This is helpful for when TMPDIR already has a trailing slash. We can't
be sure that it will on all operating systems, but this will remove it
if it is there.
> Remove trailing slashes from the $TMPDIR variable

- commands/release.go
- features/release.feature
- github/client.go
To mirror all the other `hub release` commands, allow the user to delete
releases from the command line. The new subcommand takes only one
argument (the tag of the release being deleted).
Fixes #1326
> Add ability to delete releases

- cmd/cmd.go
- features/fork.feature
This fixes a change in the behavior of hub console output introduced in d937d287037b9a24022e16337ea5e06ffdc726a.
That commit changed the way file descriptors are passed around so that commands created by `cmd.NewWithArray` have nil stdin, stdout, and stderr. I believe not passing file descriptors to the function was an oversight.
An example of a resultant change in behavior is that the `hub fork` command will error-out with code 128 when the forked repo and remote already exist, but will print no error message. Before d937d287037b9a24022e16337ea5e06ffdc726a, `hub fork` prints the normal error message in this case. I noticed this from the discussion in #1499.
Am I correct in thinking that this is a bug?
> Pass file descriptors to cmd.NewWithArray

- commands/fork.go
- features/fork.feature
Fixes #1499.
This PR makes `hub fork` succeed, with no operation, if a remote pointing to the forked repository already exists.
> Make fork command idempotent

- README.md
I checked the [Chocolatey Gallery](https://chocolatey.org/packages/hub) and it doesn't seem like there's a prerelease of `hub`. So I haven't documented that but Chocolatey itself [supports prereleases](https://chocolatey.github.io/usage.html#installing-packages).
> Document the availability of the development version.

- .gitattributes
Adds a gitattributes file that asks git to checkout the build files with unix file extensions.
The gitattibutes file marks all `.sh` files as well as all file in the `script` directory that are no `.bat` files as build files.
I have tested on my machine by running (from the git repository).
```sh
git config --global core.autocrlf true
git clone . hub2
cd hub2/script
cat -e install.sh
cat -e build
cat -e build.bat
```
Solves issue #1514. Also see pr #1516.
@mislav
> Enforce unix eol in bash script files through .gitattributes

- script/install.bat
For some reason, when the installation script is run through the VBS
wrapper on Windows 7, the `OLDPATH` gets cut in multiple parts and only
the final part makes it into the new `PATH`. This fix just collects all
the parts and concatenates them again.
> Fix PATH update in windows installation script

- features/support/completion.rb
Ignore all lines that are printed before the first command prompt. On
some systems bash prints a message about how to use the sudo command
when started with a clean `$HOME`, causing some tests to fail.
Fixes #1477
> Fix tmux_pane_content test helper

- etc/hub.bash_completion.sh
This allows the completion script to be sourced more than once while
still behaving correctly. Previously, the script would attempt to
replace `__git_list_all_commands` blindly, which would yield
multiply-replaced calls like
`__git_list_all_commands_without_hub_without_hub`.
The zsh completions already do something very similar to this to ensure
that the replacement isn't done more than once.
> Ensure that _git completion func is replaced only once.

- github/editor.go
This also considers `.exe` files. It still matches names like `foo-vim`, but it is probably safe to assume that this is in fact something vim-like.
> Fix recognition logic for vi editor variants again

- commands/fetch.go
- features/fetch.feature
This is to avoid having a writeable fork added with `git://` protocol (the default when `hub.protocol` is not configured).
This matches the behavior of `hub clone`.
Fixes #1614
> Have `fetch` use writable push URL for writeable fork

- README.md
The fish syntax highlighting was already linked below this sentence, but oddly wasn't mentioned in the sentence itself.
> Mention fish completion with bash and zsh

- commands/issue.go
- commands/pr.go
- github/client.go
> Add `hub pr list` command to list pull requests

- commands/issue.go
- commands/label.go
- features/label.feature
- github/client.go
This command lists the labels for a given repository. This command
will be enhanced with subcommands which can create new labels on the
repository and modify existing labels (i.e. renaming or changing
their colors).
Other enhancements I plan to include in the future.
* Display the labels using 256 bit colors similar to how the labels
look on GitHub. This is similar to the functionality in the
[ghi](https://github.com/stephencelis/ghi) tool.
* When displaying issues with the `issue` command, use this same
256 bit color formatting so that labels are easier to read on
terminals which don't support true colors. (e.g. `Terminal.app`)
> Add a label command

- commands/fork.go
- features/fork.feature
If user passes `origin` as the remote name
pointing to forked repository it's likely
she wants to rename origin as upstream.
> [RFC] Make fork --remote-name=origin rename origin

- commands/pull_request.go
- etc/hub.fish_completion
- features/pull_request.feature
- github/client.go
Now it's possible to add a milestone by name to a pull request instead of looking up the number. If the milestone can't be found it'll stop before creating the PR.
Closes #1089
> Add milestone to PR by name instead of number

- commands/pull_request.go
- features/pull_request.feature
Fixes #1724.
This patch omits the "Signed-off-by:" line coming from pull requests created
out of single commit messages. This way the user does not need to manually
remove their email address from the PR description.
Not introducing a flag for this as it applies to only one case (single-commit
diff between heads, as well as no -m/-f/-i specified).
Meta: sending this PR with the patched build, my Signed-off-by line is removed
automatically from the PR message.
> pull-request: Hide Signed-off-by

- cmd/cmd.go
*This is a majorly inconsequential change and saw this when I was looking through the source on my phone.*
The arguments slice is made with an initial length of 0 rather than the number of arguments that will be given, so it will be reprovisioned at least once by copying contents from the underlying array to a new one. This is work that doesn't need to be done, this PR makes the the args slice's initial length the exact number of arguments that will be appending to the slice. No array copies needed!
I could not find a contribution guide from the README, please let me know if there are any more steps through which this needs to go.
> Set slice length to known number of args

- github/template.go
- github/template_test.go
According to https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/, the `pull_request_template.md` file can also be stored in directory called `docs/`.
> Pull Request: look for templates in docs/ too

- commands/checkout.go
- features/checkout.feature
- features/pr.feature
- github/client.go
When checking out a PR, use its head ref for the default branch name so that `git push` works by default to push commits back to the PR.
With git default `push.default` setting being "simple", having the local branch name match the upstream branch name means that `git push` can work without additional arguments.
Fixes #1495
> PR checkout: ensure resulting branch is automatically pushable

- commands/pull_request.go
- features/pull_request.feature
This feature is inspired by Git's own ```git commit --amend --no-edit```. It's nice to have when scripting around Git/Hub to avoid stopping the workflow to save-and-close the text editor e.g. when firing away small fixes on multiple repos.
I create this PR using the feature itself:
```hub pull-request --no-edit```
> Create '--no-edit' option for hub pull-request

- Makefile
- coverage/coverage.go
- script/coverage
- script/test
Go has code coverage tooling for test mode, which temporarily rewrites the source code to insert annotations which will activate during the test run and track progress of executed code. Then, upon process completion, that information is dumped into a coverage report.
We can't use this approach for hub, at least not without substantial changes. First of all, hub's test coverage is mostly "from the outside", utilizing Cucumber to invoke the binary with different arguments and inspect the outputs and result. There are some tests in go, but they are minimal compared to the cukes.
Second, hub frequently aborts the process on errors via `os.Exit(1)`, and those scenarios need to be tested too. However, if the process exits prematurely, the code coverage report will never be generated.
To work …
> A method to measure code coverage across tests

- script/install.sh
- script/test
When packaging for distributions (particularly RPM), it is common
for the packaging tool to install all of the files into a chroot-
style directory structure as a non-privileged user. This is done
to avoid requiring root privileges for packaging (particularly to
avoid issues where the attempt to package causes changes to be
made to the packaging host.
The standard variable used for this (from autotools) is DESTDIR.
This patch adds DESTDIR before the prefix in install.sh to ensure
that when `make install` is run, it will direct output to the
proper location.
Signed-off-by: Stephen Gallagher <sgallagh@redhat.com>
> Add DESTDIR support for `make install`

- github/editor.go
As discussed in issue #1772 do not pass `--cmd` arguments to `vi` because they
are specific to vim.
(I have not deleted the non-grouping parentheses in the RE to help
readability.)
> Do not pass `--cmd' to vi in openTextEditor()

- README.md
I found it quite hard to find the documentation from the GitHub repo. I think the only link is in the header, and from that page I didn't find the link to documentation easily either. Might be worth adding a link in the Readme?
> Add documentation link to Readme

- commands/args.go
- commands/help.go
- commands/runner.go
- etc/hub.bash_completion.sh
- etc/hub.fish_completion
- etc/hub.zsh_completion
- features/git_compatibility.feature
- features/help.feature
- features/support/fakebin/git
- share/man/man1/hub.1.ronn
Wrap `git --list-cmds=others` command used by git built-in shell completions to add a list of hub custom commands.
Fixes #1792
> Fix integration with git 2.18 shell completions

- commands/ci_status.go
- commands/help.go
- etc/hub.zsh_completion
- features/ci_status.feature
- features/steps.rb
- github/client.go
- github/http.go
The results of Status and [Checks API](https://developer.github.com/v3/checks/runs/) are merged together.
Fixes #1787
> Have `ci-status` also query Checks API

- CONTRIBUTING.md
The contributing doc mentions a code of conduct but this links to a nonexistent URL that used to host a code of conduct that has since been abandoned. I updated it to point to the in-repo code of conduct which seems to be kept up to date.
> Update link to code of conduct

- commands/pull_request.go
- features/pull_request.feature
- github/client.go
- github/http.go
Requesting a review via `hub pull-request -r foo` would print a misleading error message that `foo` couldn't be requested for review in case `foo` was already requested per CODEOWNERS.
Fixes #1840
> Avoid re-requesting reviewers in case of CODEOWNERS

- features/ci_status.feature
- github/client.go
Older Enterprise hosts won't have Checks API, but we still want `hub ci-status` to work with them. It seems like a HTTP 403 is returned in that case, so we can safely ignore it. Also ignore HTTP 404 just in case.
Fixes #1821
> Handle more cases when Checks API is unavailable

- features/issue.feature
- github/template.go
Ignore the directory of multiple issue templates for now. In the future, there might be a way to pick a specific template from the list; this change is just to prevent crashes.
Fixes #1822
> Handle case of `.github/ISSUE_TEMPLATE` directory

- commands/ci_status.go
`response.State` extracts the state from the deprecated Github endpoint (see: https://blog.travis-ci.com/2018-09-27-deprecating-github-commit-status-api-for-github-apps-managed-repositories).
This can return "pending" even for successfully completed checks, which results in an exit code of 2:
```
$ hub ci-status --verbose xxx
✔︎      Travis CI - Pull Request        https://github.com/xxx/xxx/runs/xxx
✔︎      Travis CI - Branch              https://github.com/xxx/xxx/runs/xxx
$ echo $?
2
```
```
curl -i --header "Authorization: token xxx" https://api.github.com/repos/xxx/xxx/commits/xxx/status
{
"state": "pending",
"statuses": [
],
...
```
The exit code is determined by this switch-case: https://github.com/github/hub/blob/master/commands/ci_status.go#L108-L109
This is a proposed fix that …
> Fixed CI status check exit code.

- commands/compare.go
- features/compare.feature
There is no need to detect the current branch if a range is provided as an argument.
Fixes #1584.
> fix `compare` command if not on any branch

- commands/issue.go
- commands/pr.go
- features/pr-list.feature
- features/pull_request.feature
- github/client.go
Not sure if I understood @whatsadebugger correctly in #1913.
If instead we want to list all reviewers (not just requested ones) we
would need to make additional API requests I think.
> Add ability to list requested reviewers with `%rs`

- commands/issue.go
- commands/release.go
- features/issue.feature
- features/release.feature
- github/client.go
This commit adds the subcommand hub issue view, which displays an issue as well as
lists its comments underneath.
Addresses issue #1865
> Add the command `hub issue view <NUMBER>`

- features/pull_request.feature
- github/editor.go
This fixes #1377.
Before this fix, Markdown headers in PULL_REQUEST_TEMPLATE.md would be ignored as # is the default comment character.
>  Use 'scissors' to separate comments from PR messages 

- fixtures/test_configs.go
- github/client.go
- github/config.go
- github/config_decoder.go
- github/config_encoder.go
- github/config_service_test.go
- github/http.go
- github/http_test.go
Bringing **Unix domain socket** support to the `Hub`.
If `unix_socket` configuration is available for a given host in `~/.config/hub`, it will configure `http.Transport` that will work for `http` and `https` over **Unix domain socket**
> Add unix socket support

- commands/remote.go
- commands/remote_test.go
- features/remote_add.feature
Fixes #1832 .
This PR introduce repo visibility and permission check which will then set `isSSH` variable in GitURL method. However the tests are failing due to these errors:
The other commands that use similar method (clone and fetch) does not have such tests. Can you advice on how to fix the tests/write new tests? Thank you!
> Add repo visibility and permission check for remote add command

- Makefile
Speed up man page generation by a factor of 3 (from 18 to 6 seconds in the single-CPU case)
by not building every man page and html page several times (e.g. 24x)
> Speed up man page generation

- git/git.go
After upgrading to Git 2.20.0, all operations that relied on `hub alias`
would indefinitely hang. It can be reproduced using the following:
1. Create a new alias such as `st` for `git status`.
2. Run `hub <alias>` in a git repository.
```
$ hub st
... hangs forever
```
Inspecting the running process shows that it is executing `git help -a`
and not able to proceed. Digging into the `hub` shows that the `help`
command is called within `IsBuiltInGitCommand`. Once this entrypoint was
found, I started bisecting and found this works in 2.19.x but fails in
2.20.x. Sure enough, the Git 2.20.0 release notes [mention a
corresponding change](https://github.com/git/git/blob/master/Documentation/RelNotes/2.20.0.txt#L17-L18).
>  * "git help -a" now gives verbose output (same as "git help -av").
> …
> Restore pre-2.20.0 `git help` output

- commands/browse.go
- commands/ci_status.go
- commands/compare.go
- commands/create.go
- commands/issue.go
- commands/pr.go
- commands/pull_request.go
- commands/release.go
Indicate that long-form CLI flags are used like `--message=VALUE`, and other tweaks.
Ref. https://github.com/github/hub/issues/1819 https://github.com/github/hub/issues/1961
/cc @philwinder @devisnik @adamkaplan
> Clarify long-form CLI options

- commands/issue.go
- commands/pr.go
- commands/release.go
- features/issue.feature
- ui/ui.go
- In general, avoid using Printf without a static format string.
- Add documentation about `%n` and `%%` tokens for `--format`
Fixes https://github.com/github/hub/issues/1972
> Don't choke on literal `%` output from `--format` use

- commands/create.go
- features/create.feature
- github/localrepo.go
- github/localrepo_test.go
- No longer says "updating git remote", but not actually doing anything
- Shows a helpful warning about "origin" pointing to a possibly unrelated repo
Fixes #1849
> Improve `hub create` dealing with an existing "origin" remote

- ui/ui.go
The `ui` `Printf` and related functions return an `error` to indicate their status. But none of the call sites that are calling them are catching that returned error. Go linters see this as an un-handled error and complain about it.
What do you think about locally handling errors on stdout/stderr by just panicking and dying, removing the returned `error` from their signatures? This will get rid of the go linter warnings, and seems a little cleaner to me.
> ui Printf functions: handle errors by dying

- Makefile
If the environment variable SOURCE_DATE_EPOCH is set in the build environment, prefer it over the current date when determining the correct timestamp to use as the date the manpages were built.
See https://reproducible-builds.org/specs/source-date-epoch/
> build: embed reproducible timestamp in manpages

- Makefile
- script/build
golang does not natively respect LDFLAGS, but you can pass them on the command line using -ldflags=-extldflags=...
This is important for distributions, in order to provide common functionality such as hardening flags.
Also strip the prefixed root source directory from the embedded source file paths. This is not important information for the debugger, which should only care about paths relative to $GOPATH, and results in less build environment metadata leaking into the final binary. (This also aids in reproducible builds when using different build directories, see e.g. https://github.com/golang/go/issues/16860)
> build: respect environment LDFLAGS and strip the build path

- features/issue.feature
- github/client.go
The API result isn't guaranteed to be sorted case-insensitive, so we perform the sort in memory before displaying.
Ref. #1980
> Fix alphabetical sort of `hub issue labels` output

- Makefile
- commands/api.go
- commands/apply.go
- features/api.feature
- features/git_compatibility.feature
- features/support/env.rb
- github/client.go
- github/config.go
- github/http.go
- share/man/man1/hub.1.md
- utils/json.go
```
Usage: hub api [-t] [-X <METHOD>] [--cache <TTL>] <ENDPOINT> [-F <KEY-VALUE>]
```
- provide a low-level interface to the GitHub API that empowers GitHub users to automate their workflows via shell scripts
- close many [outstanding feature requests](https://github.com/github/hub/issues?q=is%3Aissue+is%3Aopen+label%3Afeature) in this repository that are unlikely to be implemented in hub core in the near future, but which can be easily implemented as a simple shell script using `hub api`
- make arbitrary HTTP requests to the GitHub API
- serialize GET data into query string
- serialize POST/PUT data as JSON
- read data to serialize from a file or standard input
- parse response JSON into line-based output
- cache sucessful responses
- replace `{owner}` and `{repo}` placeholders with …
> New `hub api` command for making GitHub API requests

- Makefile
This caused gcc to receive the actual argument "''" or for example "'-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now'" and then error with
gcc: error: '-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now': No such file or directory
Furthermore, the trimpath arguments tried to trim an actual path resembling "'$PWD'", which did nothing as the literal single quotes were not valid in this context.
The former issue means it is down to the go compiler to interpret -ldflags properly in order to break up the (multiple) flag values and correctly parse the extldflags, possible spaces included.
In the latter case, trimpath only accepts one argument and the shellscript already correctly double-quotes this in order to pass it as one argv[3] to the compiler:
{ "go", "build", "-gcflags", …
> Makefile: fix arguments to go, not matching what go expects

- commands/ci_status.go
- features/ci_status.feature
- github/client.go
Statuses are now sorted the same as in the GitHub web interface:
- failing first;
- then pending;
- then success/neutral;
- everything in-between is sorted alphabetically.
Fixes #2021
> Consistent ordering and `--format` support for `ci-status`

- commands/api.go
- features/api.feature
- github/client.go
- utils/args_parser.go
This is to enable nested JSON arrays/hashes.
Closes #2029, fixes #2028
/cc @mlk @fsouza
> Allow raw request body via `hub api --input <FILE>`

- commands/create.go
- features/create.feature
Hi @mislav, I've never written any go before, but I gave it a shot! Could you see if this works for [github#2025](https://github.com/github/hub/issues/2025)?
> remote name can be specified in the create command

- man-template.html
- md2roff-bin/cmd.go
- md2roff/renderer.go
Outputs the "NAME" section in roff format to fix the following:
mandb: warning: ... whatis parse for hub-alias(1) failed
Fixes #2044
> Make man pages parseable with `whatis`

- commands/api.go
- commands/ci_status.go
- commands/issue.go
- commands/pr.go
- commands/release.go
- commands/sync.go
- utils/args_parser.go
- utils/args_parser_test.go
Aims to match git-log(1) behavior:
- default: `--color=auto` (on if stdout is a TTY)
- `--color` is equivalent to `--color=always`
- `--color=never` disables color, even for TTYs
Fixes #2041
> Have commands with rich output respect the `--color` flag

- commands/issue.go
- commands/pr.go
- features/pr-list.feature
- features/support/env.rb
- github/client.go
- github/http.go
Using `%pS` outputs "draft" if the PR is in Draft state.
This still doesn't allow *creating* Draft PRs since the GitHub API doesn't expose this functionality yet.
Ref. #2038
> List PR "Draft" state using the `--format` string

- README.md
Fixes #718 by documenting that the package is in the official repository now, or perhaps there is also a need for a package for the current stable Debian version.
> Documentation of install on Debian (sid/buster)

- commands/checkout.go
- features/checkout.feature
- features/pr-checkout.feature
- features/support/fakebin/git
This fixes:
fatal: Cannot setup tracking information; starting point 'BRANCH' is not a branch.
if the remote refspec is set up to only fetch specific branches and NOT like the default `+refs/heads/*:refs/remotes/origin/*`.
I don't understand why would git, after fetching into `refs/remotes/origin/BRANCH`, complain that `origin/BRANCH` is not a branch, but there we have it. Setting up upstream tracking manually works around this problem.
Fixes #1708
> Make `checkout` work independently of remote refspec

- commands/runner.go
- features/git_compatibility.feature
Fixes this error:
$ hub --git-dir=.git
git: '' is not a git command. See 'git --help'.
Instead, help text is shown just like with normal git.
Fixes #2095
> Fix compatibility with git when run with no arguments

- commands/args.go
- commands/args_test.go
This fixes `hub -C mydir merge <URL>` and other commands that might be invoked with git global arguments by ensuring that those global arguments are also fowarded to any accompanying `git` commands found in `Before()` and `After()` chains.
This affects `create`, `fetch`, `fork`, `checkout`, `cherry-pick`, and `merge` hub commands.
Fixes https://github.com/github/hub/issues/2058
> Propagate global git arguments to Before/After chains

- README.md
Updated the readme to also include Chocolatey as an install method for Windows, instead of only listing Scoop.
> Added Chocolatey as Windows install method in the readme

- cmd/cmd.go
- commands/pull_request.go
- git/git.go
- github/util.go
Only process stdout when shelling out to git instead of combined stdout + stderr. In most cases, we want to silence stderr because we attach a custom error message to failure scenarios. In some other cases, have stderr be attached to stderr of parent process.
Fixes https://github.com/github/hub/issues/2134
> Enable GIT_TRACE

- commands/pull_request.go
This makes it clearer that commits are only added as a commented section in the case when there are multiple commits on a branch.
I'm a very new go developer, so apologies if this is a non-idiomatic change.
> Move commitLogs declaration inside multiple commits block

- commands/pull_request.go
- features/pull_request.feature
This is equivalent to unchecking the "Allow edits from maintainers" checkbox when opening a PR from the GitHub web interface.
Closes #1550
> Add `hub pull-request --no-maintainer-edits` flag

- commands/pr.go
- features/pr-show.feature
- github/branch.go
- github/localrepo.go
add the ability to open a PR page in browser (also copy & URL print to screen).
ability to open the forked PR by pass the `head` flag.
in the example above `hub` is a fork of `github/hub`.
> [pr] add ability to open Pull Request in the browser

- commands/pr.go
- commands/pull_request.go
- features/pull_request.feature
- features/steps.rb
Previously hub checked that there were [no unpushed commits](https://github.com/github/hub/blob/b3b3ebb8e517acd269489b9bd163de2f8fd309fc/commands/pull_request.go#L219-L223) but this check doesn't work when there is not even a remote branch.
**Before**
**After**
This fixes #1930.
> check head branch exists before creating PR

- commands/api.go
- commands/commands.go
- features/api.feature
- github/client.go
- utils/json.go
REST resources are paginated by following the `<next>` link in the "Link" response header.
A GraphQL query has to accept the optional `endCursor` string variable and output `pageInfo`:
```graphql
pageInfo {
hasNextPage
endCursor
}
```
Full GraphQL example: find all repositories owned by USER:
```sh
hub api --paginate graphql -f owner="USER" -f query='
query($owner: String!, $per_page: Int = 100, $endCursor: String) {
repositoryOwner(login: $owner) {
repositories(first: $per_page, after: $endCursor, ownerAffiliations: OWNER) {
nodes {
nameWithOwner
}
pageInfo {
hasNextPage
endCursor
}
}
}
}
'
```
https://developer.github.com/v3/#pagination
https://developer.github.com/v4/guides/resource-limitations/#node-limit
> Implement `hub api --paginate`

- Makefile
- script/build
When go autodetects that it is being run as a go mod, and that there is a vendor directory, it will still try to redownload all sources over the network, unless you use -mod=vendor to tell it to use that. Additionally, when using -mod=vendor the compiler will nicely avoid messing with $GOPATH at all, since it can operate in a completely self-contained manner.
Take advantage of this, when the detected go version is at least 1.11 (when the -mod flag was introduced).
> build: pass mod vendoring flag on newer versions of go

- commands/pull_request.go
This was tripping me up for so long. I eventually discovered the problem was my spaces, re. https://github.com/github/hub/issues/1287#issuecomment-250454584.
> Docs: mention that comma-separated lists must not have spaces

- features/pull_request.feature
- github/branch.go
- github/localrepo.go
When `git config push.default` is "upstream" or "tracking", but the current branch is pushed to a remote _without_ having upstream configuration set up (for example, via `git push <REMOTE> HEAD` without `-u`), this change makes it so that the remote tracking branch (the push target) is still discovered via the same mechanism as if `push.default` wasn't set (i.e. iterating through all the remotes).
Fixes https://github.com/github/hub/issues/189#issuecomment-508122178 /cc @lestephane
> Improve push target detection for `push.default=upstream`

- features/authentication.feature
- github/client.go
- github/config.go
When supplied with GITHUB_TOKEN, hub will attempt to request the `user` API resource which isn't available in the context of Actions.
To work around this, scripts may now set GITHUB_USER to avoid hitting the unavailable API resource.
The actual value of GITHUB_USER is not used in most commands; therefore, it can be a name of an organization or even a dummy value.
Fixes #2149
> Allow hub used in Actions by specifying GITHUB_USER

- commands/help.go
- commands/issue.go
- commands/pull_request.go
- commands/runner.go
- github/util.go
- md2roff/renderer.go
- ui/format.go
- Use bytes.Equal instead of bytes.Compare
- Use time.Since instead of manual timestamp subtracting
- Use sort.Strings instead of sort.StringSlice
- No need to specify the len of the slice
> Simplify code

- github/config.go
os.Kill can not be signal trapped. I assume we want to trap syscall.SIGTERM
instead?
> Trap syscall.SIGTERM instead of os.Kill

- README.md
- We're (slowly) moving away from the Linuxbrew name, now that it's officially a part of Homebrew.
> README: Replace "Linuxbrew" with "Homebrew on macOS or Linux"

- commands/runner.go
Calling hub with one or more options but no subcommand resulted in the
following error message trying to expand an empty string as an alias:
error: key does not contain variable name: alias.
This fixes the root cause: attempting to retrieve an invalid config key.
> Fix error message on hub --paginate

- Makefile
`go` supports environmentally-toggled support for the module system introduced in `1.11`.
Currently the Makefile checks for go > `1.10` to decide whether or not to use the `-mod` flag; for certain `go` installations, though, this flag is unsupported without setting `GO111MODULE=on` in the environment. 
Compounding this is having a module that depends on go >= `1.12`. If modules are disabled, everything builds fine; if they are enabled any Go version under `1.12` (even if it has backported module support) will fail.
This PR:
- only enables module use for `go` >= `1.12`
- sets `GO111MODULE=on` if modules are enabled
> Tweak Makefile to support older Go versions' backported module support

- commands/api.go
- features/api.feature
Fixes https://github.com/github/hub/issues/2234
> hub api url generation fixes

- README.md
Adds a section for installing `hub` on Ubuntu with `Snap`
> Updated README.md with Ubuntu Snap install instructions

- features/authentication.feature
- github/config.go
- share/man/man1/hub.1.md
Previously, hub enabled usage within Actions if GITHUB_USER was explicitly specified https://github.com/github/hub/releases/tag/v2.12.3
To make this step optional for the user, hub now infers GITHUB_USER from the first part of GITHUB_REPOSITORY which should be a value [set by default within Action runs](https://help.github.com/en/articles/virtual-environments-for-github-actions#environment-variables).
Ref. https://github.com/github/hub/issues/2249
> Make hub easier to use from GitHub Actions

- etc/hub.fish_completion
* Redefined `__fish_hub_using_command` to support multiple commands (such as `hub pr list`)
* Added `hub pr list` and `hub pr checkout` along with their options
> Added `hub pr` fish completions and wrapped `git` completions

- git/ssh_config.go
Use `homedir.Dir()` instead of `Getenv("HOME")` on Windows to look up `~/.ssh/config` in the correct location.
Fixes #2270
> Fix parsing `~/.ssh/config` on Windows

- commands/compare.go
- features/compare.feature
- Correctly detect when the current branch is pushed to a fork
- Support upstream configuration with full remote URL
- Allow `/` in branch names
- More precise errors instead of just printing usage synopsis:
- no current branch
- the current branch doesn't seem pushed to a remote
- the current branch is the same as the default branch
- `--base` value is the same as current branch
Closes https://github.com/github/hub/issues/1697, closes https://github.com/github/hub/issues/1808
> Improve `compare` upstream detection & documentation

- etc/hub.bash_completion.sh
- features/bash_completion.feature
Based on the manual page for git fork, this pull request adds `--remote-name` and `--org` completions, waiting for user-provided free-text as arguments to both. It also considers the `--remote-name` and `--no-remote` flags to be mutually exclusive. See commit messages for details.
Fixes #2108.
> Add completions for git fork

- commands/pr.go
- features/pr-show.feature
Adds the same formatting for `pr show` that are used in `pr list`. The format option supercedes the copy `-c, --copy` or url `-u, --url` flags and instead prints out the information from the git api. I choose not to remove `--url` for now to not break any existing scripts that use that flag.
> implement format for `pr show` for #2288

- README.md
I just added a link to the apt package manager from Debian man pages.
> [docs] Add link to apt package manager

- commands/gist.go
- commands/help.go
- features/authentication.feature
- features/gist.feature
- features/git_compatibility.feature
- github/client.go
This addresses #2226 and #2116 by creating a `gist` subcommand.
This allows you to both create and retrieve gists. When creating a gist it can be public or private.
In order to do this, the `gist` scope is added to the token we request.
Closes: #2226
Closes: #2116
Signed-off-by: Phil Dibowitz <phil@ipom.com>
> Make a gist command

- commands/pull_request.go
- features/pull_request.feature
The Signed-off-by string already gets stripped, so I extended the regular expression to also match Co-authored-by.
Resolves #2311
> Strip co-author from PR descriptions

- .gitignore
- Makefile
- commands/help.go
- commands/runner.go
- features/help.feature
- features/support/fakebin/git
- script/install.sh
- script/package
- script/publish-release
- script/test
- Support compressed man pages by delegating to `man <arg>`
- Enable `hub help --web <command>`
- Respect `git config help.format`
Fixes #2228, closes #2298
> Restructure manpage-based help format

- commands/api.go
- features/api.feature
- github/http.go
Previously, calling `hub api --paginate` with any substantial list of results would exhaust the Ratelimit allocation, since `hub api` did not pause before requesting the next page. With this change, `hub api` will check the rate limit headers and sleep until "Reset" if calling for the next page would exceed the limit.
> Honor the rate limit headers in "hub api"

- script/version
I noticed while trying to build `hub` from an unpacked archive inside an unrelated repository (https://github.com/git-for-windows/MINGW-packages) that `script/version` was happy to pick up incorrect tags.
This PR fixes that.
> `script/version`: make sure to look at the correct `.git/` directory

- commands/issue.go
- features/pr-list.feature
- features/steps.rb
This makes the behavior consistent with other git commands.
Also fix up a bug in the documentation of `--color`.
> commands: consult global color.ui setting when --color=auto

- fixtures/test_configs.go
- github/config_decoder.go
- github/config_service_test.go
In my first time to use `hub`, my configuration file was incorrect.
And `hub` was crushed because of failed to type conversion. Please see #2379.
I added type check into the YAML configuration decoder.
Now, `hub` won't crush even if given an incorrect configuration file. It will just ignored it.
I think probably it more friendly if reporting about incorrect configuration.
But I didn't edit except a configuration decoder at the moment.
> Add type assertion test to YAML config decoder

- etc/hub.bash_completion.sh
This change accounts for uses who might have an alias set to grep which is not compatible with `grep -E` (e.g. `alias grep=rg`)
> use `command grep` vs `grep`

- features/pull_request.feature
- github/http.go
Go's `net/http` will intentionally change the HTTP method being used after a 301, 302, or 303 redirect for a non-GET request.
When encountering a 301 or 302 response codes, fail any non-GET request with an tip that 308 and 307 should be used, respectively.
Fixes #2439
> Refuse to follow HTTP 301, 302 redirects for non-GET requests

- commands/api.go
- features/api.feature
- features/authentication.feature
- features/gist.feature
- github/client.go
- github/http.go
- If a 403 is due to SSO challenge, display the URL to authorize the token
- If a 403/404 is due to insufficient OAuth tokens, display the notice
Fixes #2147
> Print more user-friendly HTTP 40x errors

- commands/issue.go
- commands/pull_request.go
- commands/release.go
- features/issue.feature
- utils/args_parser.go
This PR adds the ability to edit existing issues using the same interface as `hub issue create`. 
There is a little duplication between creating and editing issues that could be removed. I'm not convinced that removing the duplication would increase clarity and readability.
> Add the ability to edit issues

- README.md
- script/get
Also adds a simple cross-platform download script that works across all Actions environments: Ubuntu, macOS, and Windows.
Fixes #2249, closes #2259, fixes #987, closes #1585
> Add instructions for GitHub Actions

- git/git.go
- github/localrepo.go
This affects reading the current branch as well as reading the default branch for a remote. Because we're no longer trying to read the ref manually from the filesystem, this approach works with git worktrees.
Fixes #2484, closes #2485
> Use `git symbolic-ref` to read the branch name for HEAD

- README.md
Fixes #2475.
Tiny PR. When installing `hub` via a Linux Snap in a terminal, `sudo` needs to be used for the majority of users.
> Update snap install command.

- README.md
`hub` is packaged by openSUSE. This PR adds openSUSE and the coresponding
package manager to the installation instructions.
> Add openSUSE and zypper to install instructions

- etc/hub.fish_completion
We expand on some long options, and add a couple of options that were previously missing.
> Add more Fish completions to pull-request

- README.md
see https://github.com/conda-forge/hub-feedstock for conda-forge hub package for all platforms.
> Update README to include hub on conda forge for all platforms

- commands/help.go
- commands/pr.go
- github/client.go
- github/http.go
Initially this was just a small hack in my local `hub` repo. After having used it without any issues almost every day for the past two years, I thought I would open this PR for discussion to see if others are also interested.
Personally, I find it super convenient not having to open a browser/website to **merge a PR** (which I usually create from command line as well using `hub pull-request`).
The GitHub API has offered a "merge" functionality for a long time:
```
PUT /repos/:owner/:repo/pulls/:pull_number/merge
```
See https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button
So far, this was not supported by `hub`.
I added a new `hub pr merge <PR-NUMBER>` command that takes the PR number and merges the PR (if the user has write access to the repo).
Note: This is the first …
> Implement PR merge command

- .github/workflows/ci.yml
Update checkout and cache used in GitHub Actions workflow to v2
* [actions/checkout](https://github.com/actions/checkout)
* [actions/cache](https://github.com/actions/cache)
> fix: Update checkout and cache to v2

- github/config.go
The docs at os/signal.Notify warn about this signal delivery loss bug at
https://golang.org/pkg/os/signal/#Notify, which says:
Package signal will not block sending to c: the caller must ensure
that c has sufficient buffer space to keep up with the expected signal
rate. For a channel used for notification of just one signal value,
a buffer of size 1 is sufficient.
Caught by a static analysis tool from Orijtech, Inc. called "sigchanyzer"
> github: fix unbuffered channel passed to signal.Notify

- github/client.go
I'm working on a project that has a complex CI setup, and uses more than 30 CI jobs. Sometimes `hub ci-status` would report success when it was still pending, which was very annoying, because it was only checking the first 30.
`per_page=100` is used in many other queries, and is the maximum that is allowed without paging.
> Allow up to 100 CI checks for CI status command
