github/config.go

Reference: https://github.com/github/hub/issues/769

Fix prompt for user host for GHE

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/mattn/go-isatty/isatty_bsd.go

With this change i'm able to run hub on OpenBSD.
Regards,
Fabian

update mattn/go-isatty dep to support OpenBSD

---

commands/init.go
features/init.feature

Support `hub init -g DIR`

---

git/git.go
git/git_test.go

Check for empty git config

---

commands/pull_request.go
features/pull_request.feature
github/client.go

Sorry too lazy to figure out how to make a unit test for this :-(

Allow assigning a new PR to a user, closes #371

---

.travis.yml
features/support/completion.rb
script/bootstrap
script/cached-bundle
script/s3-put

Adding OSX build to Travis. Build time has increased 4 times. But it helps reduce cross platform issues.

Add OSX build to Travis

---

commands/issue.go
commands/pull_request_tpl.go
commands/pull_request_tpl_test.go
commands/release_tpl.go
commands/release_tpl_test.go
features/pull_request.feature

* Put "The" before description
* Add comma
* Reflow to 80 columns

Update EDITMSG copy

---

CONTRIBUTING.md

We are intending to adopt the soon-to-be-announced [Open Code of Conduct](http://todogroup.org/opencodeofconduct) for all @github projects. This adds it to the contributing guidelines. Let me know if you have any questions or concerns.

Code of Conduct

---

commands/merge.go
features/merge.feature

Allow --ff with merge

---

script/bootstrap

Related PR: https://github.com/github/hub/pull/797

Update `script/bootstrap` to recommended Go and Ruby version

---

commands/compare.go
features/compare.feature

Adds -b option to compare that specifies the base.
related feature request: #917

Add base option to compare

---

features/pull_request.feature
features/steps.rb
fixtures/test_repo.go
git/git_test.go
github/hosts.go
github/localrepo.go
github/project.go
github/remote.go
github/remote_test.go

Please see PR #1019 for previous discussion.

Another attempt at fixing pull-request command for fetch-only remotes.

---

commands/apply.go
commands/browse.go
commands/checkout.go
commands/cherry_pick.go
commands/ci_status.go
commands/clone.go
commands/compare.go
commands/create.go
commands/fetch.go
commands/fork.go
commands/init.go
commands/issue.go
commands/merge.go
commands/pull_request.go
commands/push.go
commands/remote.go
commands/submodule.go

followup to #1073 where I was reminded that `gh` is now called `hub`
took the liberty to change docs in all files
/cc @jingweno @mislav thanks

rename gh command to hub in docs

---

commands/release.go

Resolves #820.
I see this command has no Cucumber tests. I'm too inexperienced to write one I think. I tested the new flag manually: it works fine. Let me know what you think. Thanks!

Add new flag to "release" for specifying commitish

---

script/cross-compile
script/package

Updating the cross compile script here to add support for arm processors.

Adding support for arm processors

---

commands/issue.go
features/issue.feature
features/steps.rb

* Supports displaying project issues and pull requests assigned to a particular user

Filter project issues by assignee

---

github/client.go

This introduces no change at all, but start cleaning up the usage of octokit.

Don't use octokit in GhLatestTagName.

---

commands/checkout.go

Just a very trivial refactoring of checkout command logic

Trivial refactoring of checkout command

---

features/authentication.feature
github/config.go
github/config_service.go

Check if config location is writeable before authenticating

---

README.md
commands/alias.go
etc/README.md
etc/hub.fish_completion
features/alias.feature

Fish completion

---

commands/fork.go
features/fork.feature
github/client.go

Add a `--org` flag to `hub fork`

---

commands/alias.go
features/alias.feature

Add plan9port rc shell support to `hub alias`

Add plan9port rc shell support

---

CODE_OF_CONDUCT.md

Our pledge to making participation in the hub project and its community a harassment-free experience for everyone.

Contributor Covenant Code of Conduct

---

share/man/man1/hub.1.ronn

Fixes https://github.com/github/hub/issues/1551, closes https://github.com/github/hub/pull/1562

Document available environment variables

---

features/release.feature
github/client.go

As suggested at #1511, instead of fetching only the first 30 releases,
follow the `next` link to fetch all pages.

Fetch all releases when doing `hub release`

---

commands/pull_request.go
features/pull_request.feature
github/http.go

Enable team reviewers in `pull-request`

---

commands/compare.go
commands/help.go

Also document -b option for compare command

Document sync command in help

---

commands/create.go
features/create.feature
github/client.go

Prevent setting a public upstream when creating a private repo.

---

commands/pull_request.go

Update --labels documentation to show it will be created if not exists

---

utils/utils.go
utils/utils_test.go

Making the TimeAgo method testable

Adding unit tests for util methods

---

commands/issue.go
commands/pr.go
features/pr-list.feature
github/client.go

* Support `--state=merged`
* Add merged date information to custom format
* Add base/head/merge commit SHA information to custom format
Ref. https://github.com/github/hub/issues/1815
/cc @DennisSchiefer @itaranto

Add more information about merged PRs in `hub pr list`

---

github/http.go

Dial is deprecated as of Go 1.7, replaced with DialContext.
This PR updates it to avoid the deprecation warning.

Replace deprecated Dial with DialContext

---

cmd/cmd.go

Fix subcommand execution under WSL

---

commands/api.go
features/api.feature
github/client.go
github/http.go

Followup to https://github.com/github/hub/pull/2016

Add HTTP request/response headers functionality to `hub api`

---

commands/commands.go
commands/commands_test.go
commands/remote.go
commands/remote_test.go

These are allowed on GitHub.
Ref. https://github.com/github/hub/issues/2087

Allow repository names that start with a dash character

---

commands/issue.go
features/issue.feature

Fix issue/PR labels output in no-color mode

---

commands/pull_request.go
features/pull_request.feature
github/client.go
github/http.go

Thank you @thehunt33r for the initial implementation!
Fixes #2038

Open draft pull requests with `-d` / `--draft`

---

.gitignore

I'm not ready to give up vim, but sometimes I like trying other editors and git caught this in my dirty state. Seems wise to guard against?

Ignore VSCode

---

commands/issue.go
commands/pull_request.go
features/issue.feature
github/client.go

I adapted the suggestion in https://github.com/github/hub/issues/2155#issuecomment-498217736 to pass a name to the milestone instead of an id.

Add a milestone name instead of an id, when creating 

---

commands/runner_test.go
git/git_test.go

Don't assign values we don't end up checking.

Fixed ineffectual assignments in tests

---

github/config.go
utils/color.go

No need to covert these types.

Avoid unnecessary conversions

---

commands/pr.go

Fixes https://github.com/github/hub/issues/2182

Remove NC/Nc from pr list formatting

---

commands/sync.go
features/sync.feature

Change quotes in Sync command to be consistent with Git style

---

commands/release.go
features/release.feature

Add support for `hub download --include` flag

---

index.html

Adds Google Analytics to landing page.

Add Google Analytics to landing page

---

man-template.html

Adds Google Analytics to man page template.

Add Google Analytics to man page template

---

github/project.go
github/project_test.go

use strings.EqualFold instead of strings.ToLower with equal
operation when comparing string ignore case
BenchmarkSameAsToLower-8     	29738065	        39.1 ns/op	       0 B/op	       0 allocs/op
BenchmarkSameAsEqualFold-8   	42597748	        25.5 ns/op	       0 B/op	       0 allocs/op

improve Project SameAs logic

---

index.html

This way it's easier to skim instead of always having to read commments
for explanations.

Use full option names in examples

---

script/get

Convert case upper to lower in the get script for GitHub Actions.
```diff
- Location
+ location
```

Fix case upper to lower

---

utils/args_parser.go
utils/args_parser_test.go

Fix parsing boolean flags with explicit values
